Dear $reporter,

Your Fault Report has been rectified. The following are the details of the
completed processes of the Fault Report.


Fault Report
Report Date/Time: $report_date
Category:   $category_name
Fault Date:    $fault_date
Description:	$fault_description

Rectification 
Rectification Date/Time:  $rectify_date
Rectified by:  $rectified_by
Rectification  Remarks:  $rectify_remark

Completion
Completion Date/Time:  $completion_date
Completed by:  $completed_by
Completion Remarks:  $completion_remark


Thank you.

FiGi Administrator

