Dear $reporter

Thank you for reporting a Fault via the FiGi system.
The following are the deatils of the Fault reported by you.

Reporter: $reporter
Report Date/Time: $report_date
Category:   $category_name
Fault Date:	$fault_date
Remarks:	$fault_description

We will follow up on your Fault Report as soon as possible. 
Please visit $figi_url for he latest status of your Fault Report.

Thank you.

FiGi Administrator


