Dear $requester,

Your department has been issued with the following equipment

Request Date/Time: $request_date
Category: $category_name
Loan Date: $loan_date
Return Date/Time: $return_date
Quantity: $quantity
Remarks from Receiver: $receive_remark
Items:  $item_list
Accessories: $accessories_list

We note that the equipment will be taken care by you in good condition.
 
Thank you.

FiGi Administrator

