Dear $requester,

Your Loan Request has been approved by HOD. 

The Administrator will get in touch with you as soon as the equipment is ready for collection.

Request Date/Time: $request_date
Approval Date/Time: $approval_date
Approved by: $approver    
Category: $category_name
Loan Period: $start_loan to $end_loan
Quantity:   $quantity
Purpose: $purpose
Remarks from Requestor:	$remark
Remarks from Approver:	$approval_remark

Please visit $figi_url to check the status of your Loan Request.

Thank you.

FiGi Administrator
