Dear $requester,

You have been returned some equipments:
$returned_item_list

Returned By: $returned_by_name
Return Date/Time: $return_date
Return Remark: $return_remark
Received By: $received_by_name
Received Remark: $receive_remark


Below are the detail request for your reference.

Request Info
	Date/Time: $request_date
	Category: $category_name
	Loan Date: $loan_date
	Projected Return Date/Time: $return_date
	Quantity: $quantity
	Purpose: $purpose
	Remark: $remark

Issue-Out Info
	Quick Loan: $is_quick_loan
	Issued By: $issued_by_name
	Issue Date/Time: $issue_date
	Issue Remark: $issue_remark
	Loaned By: $loaned_by_name
	Loan Remark: $loan_remark

Loan-Out Items 
$item_list



Thank you for returning the item in good condition.

Thank you,
FiGi Administrator

