Dear $requester,

You have been issued with the following equipment
$item_list

Request Info
	Date/Time: $request_date
	Category: $category_name
	Loan Date: $loan_date
	Projected Return Date/Time: $return_date
	Quantity: $quantity
	Purpose: $purpose
	Remark: $remark

Issue-Out Info
	Quick Loan: $is_quick_loan
	Issued By: $issued_by_name
	Issue Date/Time: $issue_date
	Issue Remark: $issue_remark
	Loaned By: $loaned_by_name
	Loan Remark: $loan_remark


We note that the equipment loaned out to you will be taken care of in good condition.
 
Thank you.

FiGi Administrator

