Dear $requester,

Your request has been unapproved. Please check following request info and un-approval remarks

Request Date/Time: $request_date
Approval Date/Time: $reject_date
Approved by: $rejected_by_name
Category: $category_name
Loan Period: $start_loan to $end_loan
Quantity: $quantity
Purpose: $purpose
Remarks from Requestor:	$remark
Remarks from Approver:	$reject_remark


Thank you,
FiGi Administrator
