Dear $requester,

This is a Gentle Reminder that the equipment currently loaned out to you has reached its Due Return Date.
Please contact Administrator as soon as possible to continue your loan.

Date of Request: $request_date
Loan Date: $loan_date
Return Date/Time: $return_date
Category: $category_name
Quantity: $quantity
Purpose: $purpose
Remarks: $remark 
Items: $item_list

We look forward the return of the equipment.

Thank you.

FiGi Administrator

