Dear $requester,

This email is a reminder for you that your loan should be returned by today. Please check following loan request.

Date of Request: $request_date
Loan Date: $loan_date
Return Date/Time: $return_date
Category: $category_name
Quantity: $quantity
Purpose: $purpose
Remarks: $remark 
Items:  
$item_list

Thank you for returning the item in good condition.

Thank you,
FiGi Administrator

