Dear $requester,

Your service request has been completed. Please check following request detail:

Service Request Info
Date/Time:   $request_datetime
Category:   $category_name
Expected Service Date:  $expected_service_datetime 
Purpose: $purpose 
Remark:	$remark

Service Preparation Info
Prepare Date/Time: $prepare_datetime
Prepared by: $prepared_by    
Preparation Remark: $prepare_remark

Service Completion Info
Complete Date/Time: $complete_datetime
Completed by: $completed_by
Completion remark: $complete_remark

Please visit $figi_url to check the status of your request.

Thank you,
FiGi Administrator


