Dear $requester,

Your service request has been prepared. Please check following request detail:

Service Request Info
Date/Time:   $request_datetime
Category:   $category_name
Expected Service Date:  $expected_service_datetime 
Purpose: $purpose 
Remark:	$remark

Service Preparation Info
Prepare Date/Time: $prepare_datetime
Prepared by: $prepared_by    
Remark: $prepare_remark

Please visit $figi_url to check the status of your request.

Thank you,
FiGi Administrator


