Dear $requester,

Your service request has been rejected. Please check following request detail:

Request Date:   $request_date
Request Time:   $request_time
Approval Date:  $approval_date
Approval Time:  $approval_time
Approved by:    $approver    
Category:   $category_name
Service Date:    $start_loan 
Remarks from Requestor:	$remark
Remarks from Approver:	$approval_remark

Please visit $figi_url to check the status of your request.

Thank you,
FiGi Administrator


